spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace